엔티티 추가
koreatech/hanpyo-server pull request #7
Opened 2021-03-23 14:38 UTC by youngxpepp

## 📑 제목

<필수> 엔티티 추가

<선택> 이미지 첨부

## 💬 작업 내용

> 구현 내용 및 작업 했던 내역

- [x] Cart 엔티티 추가
- [x] Lecture 엔티티 추가
- [x] LectureTime 엔티티 추가
- [x] Member 엔티티 추가
- [x] PersonalSchedule 엔티티 추가
- [x] TimeTable 엔티티 추가

## 🚧 PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- Soft delete 추가해야 함
- startTime, endTime을 JSON으로 저장했을 때와 별도의 테이블로 분류했을 때 성능 차이
  - DB 부하
  - 어플리케이션 부하

2021-03-23 15:17 UTC, Do-ho requested changes
협업하느라 고생하셨습니다 ㅠㅠ

2021-03-23 15:17 UTC, Do-ho commented on src/main/java/com/github/hanpyo/entity/Lecture.java
> +	private Integer divisionNumber;
오타가 있네요...!

```lecture_divistion_number``` => ```lecture_division_number```

2021-03-24 04:24 UTC, youngxpepp commented on src/main/java/com/github/hanpyo/entity/Lecture.java
> +	private Integer divisionNumber;
오타 수정했어요 확인부탁드려요ㅎㅎ

2021-03-24 05:14 UTC, Do-ho approved these changes
고생하셨습니다!!

2021-03-24 05:37 UTC, merged