XML Parser 제작
koreatech/hanpyo-server pull request #9
Opened 2021-04-01 07:17 UTC by Do-ho

## 📑 제목

XML Parser 제작

## 💬 작업 내용

> 구현 내용 및 작업 했던 내역

- [x] RestTemplate를 통한 과목 정보 받아오기
- [x] XML를 DOM으로 만들어 과목 ID와 정보 얻어오기

## 🚧 PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 부족한 코드지만 잘 부탁드려요...!

2021-04-01 13:22 UTC, youngxpepp requested changes
RestTemplate을 사용하는 것조차 놀라웠는데, MockTest까지 적용하시다니..
코드 정말 잘 봤습니다!

2021-04-01 13:22 UTC, youngxpepp commented on src/main/java/com/github/hanpyo/util/LectureGetter.java
> +    public static RestTemplate restTpl = new RestTemplate();
RestTemplate은 Connection Pool을 사용해야 할 것 같아요.
https://nesoy.github.io/articles/2020-05/RestTemplate

또한 Bean으로 만드는건 어떨까요? 아래 링크를 참조하면 RestTemplate을 Bean으로 만들더라구요.
RestTemplate이 LectureGetter 뿐만 아니라 다른 곳에서 쓰일 수도 있고, RestTemplateBuilder를 이용해서 만들면 더 편한 장점도 있습니다. 
https://cheese10yun.github.io/spring-guide-api-call/

2021-04-01 13:22 UTC, youngxpepp commented on src/main/java/com/github/hanpyo/util/LectureGetter.java
> +public abstract class LectureGetter {
Bean은 Bean에서만 쓸 수 있어요. RestTemplate이 Bean이 되면 LectureGetter도 Bean이 되겠죠? 
abstract 키워드말고 그냥 클래스로 선언하는건 어떨까요?

2021-04-01 13:22 UTC, youngxpepp commented on src/main/java/com/github/hanpyo/util/LectureGetter.java
> +    }
String으로 반환해주는 것보다 객체로 반환하는 것이 좋아보여요. XML을 객체로 변환하여 반환하면 해당 API가 정확히 어떤 데이터를 응답하는지 직관적으로 알 수 있을 것 같습니당. 아래 링크는 XML을 객체로 변환하는 글이에용ㅎㅎ

- https://blog.kingbbode.com/6
- https://zero-gravity.tistory.com/288

2021-04-01 13:22 UTC, youngxpepp commented on src/main/java/com/github/hanpyo/util/XMLParser.java
> +}
XMLParser가 존재해야 하는 이유는 명확하다고 생각합니다. 하지만, 제가 위에서 말씀드린 예제를 보면 RestTemplate 쪽에서 이미 변환을 제공해주는 듯 해요.

2021-04-05 09:59 UTC, Do-ho commented on src/main/java/com/github/hanpyo/util/LectureGetter.java
> +    }
추후에 바꿔보겠습니다!

2021-05-02 07:00 UTC, merged